(defun perfectos (x y)
    (dotimes (i x)
        (format t "~%")
        (dotimes (i y)
            (format t "+ ")
        )
    )
)

(format t "Altura de la caja: ")
(defvar x (read))
(format t "Ancho de la caja: ")
(defvar y (read))
(perfectos x y)
