(defun iguales (lista)
    (setf i 0)
    (format t "~%~%Todos los elementos de la lista son iguales?")
    (setf x (nth 0 lista))
    (loop 
        for xi in lista until (not(= xi x))
        do
        (setf i (+ i 1))
    )    
    (if (= i (length lista))
        (format t "~%Si")
        (format t "~%No")
    )
)

(format t "Cuantos elementos tiene su lista?: ")
(defvar n (read))
(format t "~%Ingrese los elementos de la lista:~%")
(defvar lista nil)
(defvar e)
(dotimes (i n)
    (format t "Elemento de la lista: ")
    (setq e (read))
    (setq lista (cons e lista))
)
(setf lista (reverse lista))
(format t "~%Lista: ~a" lista)

(iguales lista)
